  services:
    server:
      container_name: server3
      image: server3
      build:
        context: .
        dockerfile: DockerFile
      volumes:
        - /node_modules
      ports:
        - 4002:4002
